### ISSUE TITLE
Node.js ≥ 14 / node-ffi-napi instability (random v8 crash)

### ISSUE THREAD

**Issue by xan105** [xan105/node-processMonitor#1]
node-ffi-napi #97

**Comment by pl4yradam** [comment]
Any update on this? The app seems to not build with this

**Comment by xan105** [comment]
I haven't tested it in a while with Node 14 but I didn't see any progress in the node-ffi-napi repo.
But this issue is only when using it not installing it.

If you can't build node-ffi-napi that's another issue.
You need the correct build tools installed for that.

> Prequisites: C/C++ build tools (Visual Studio) and Python 2.7 (node-gyp) in order to build ffi-napi.

I suggest to google it or you may want to give https://www.npmjs.com/package/windows-build-tools a try
