### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by gulbrillo** [xan105/node-processMonitor#3]
On a machine that was creating hundreds of processes a second, the process monitor resulted in an increase of RAM usage (compiled Electron app) of roughly 1 MB per second. After a day, the app required 10 GB of RAM. We were able to trace this back to `WQL.createEventSink()` - RAM usage increase stopped when `WQL.closeEventSink()` was called.

**Comment by xan105** [comment]
I'm not sure how to tackle such issue to be honest. I'm not that proficient in C++.

`WQL.closeEventSink()` close every resource opened for the eventsink and cancel the running async wql query so it's normal _I think_ that ram usage stopped once called as there is no event received anymore when closed and everything is released.
I've tried to release said resource after subscribing without canceling the query to test it out. But it didn't change anything in the memory consumption and from what I've read I'm not even sure I'm suppose to if I want to get the next event. Altho I still received some.

I just found one [reference I might have forgotten to release](https://github.com/xan105/node-processMonitor/commit/53fca73eac7570528b690e50bf4cc12213992945) :
>IUnknown* str = vtProp;
>
>This assignment uses operator IUnknown* of the _variant_t class, which implicitly calls an AddRef() on the object. 
>So str->Release() needs to be called after usage, VariantClear(&vtProp) is not enough to decrement the ref count of the object

but it didn't change anything anyway.

I don't know if it is a problem with node-ffi-napi, or my code, or the way the callback is prevented to be garbage collected in js.

I had to literally _spam_ my system with process creation to somehow replicate this.
In a more '_normal use_' I'm using this in another project which has a running node background process to monitor process event and I have never noticed such an increase of memory in all my testing and usage; but it was affected as Electron when _spamming_ tho it was considerably slower.
The memory is eventually bring back to it's initial level over time (garbage collector ?).

Thank you for bringing this to my attention and I'm sorry if it has cause you any inconvenience 
but I'm afraid I'm at my wits' end here.

**Comment by gulbrillo** [comment]
Thanks so much for looking into this. :) We were so grateful that this module existed as we needed our Electron app to perform actions when a specific external process was started.

The excessive memory consumption (10 GB) was only observed by one tester, and yes, their system was spamming some creation/deletion of NetCfgNotifyObjectHost.exe every few milliseconds (which seems to be a bug in Windows). This additionally causing a 20% CPU load by the process monitor. For all other testers the memory consumption was perfectly fine (50 to 100 MB) and CPU load is at 0 to 0.1%.

Unfortunately my C++ knowledge is close to zero. We will keep an eye on it and do some more testing. :)

**Comment by xan105** [comment]
>to perform actions when a specific external process was started

Idk if this will be helpful or not but I've added a whitelist option. So the WMI query will only 'react' to the specified list of binary. 
This way the probability to have an issue should be dramatically reduced. 

I've done some preliminary testing and all seems _ok_ but I'll do some more _tomorrow_ before pushing any update over npm.
~I'll keep you posted~ uploaded to npm (1.4.0)

**Comment by gulbrillo** [comment]
oh that's awesome!! we had an issue where some few users required watching an admin process while 99% didn't ... the whitelist will do exactly what we need. :) will be implementing it today. Thanks!! :)
I did run into another problem, will open a new issue...

**Comment by gulbrillo** [comment]
We implemented and tested 1.4.0 and I can confirm that this solves the memory leak issue on the buggy windows installation. Thanks again! :)
