### ISSUE TITLE
ERR_WQL_QUERY_FAILED

### ISSUE THREAD

**Issue by gulbrillo** [xan105/node-processMonitor#4]
Sometimes [after wake from standby(?), not really reproducible unfortunately]  
`wql-process-monitor\lib\processMonitor.cjs`
throws
`if (!result) throw "ERR_WQL_QUERY_FAILED";`
without any indication what went wrong.

**Comment by xan105** [comment]
It means the WQL query (a SQL-ish query like) to Windows' WMI failed. 
Usually it's from bad syntax or wrong usage.

It can only happen after "subscribing". Having this error after a wake from standby is rather odd.

What is your usage of [subscribe()](https://github.com/xan105/node-processMonitor#subscribeobj-option--eventemitter) ?
It should be called only once after the event sink is initialized. And you should only have to deal with the returned event emitter hence after.

**Comment by gulbrillo** [comment]
Here is my current code snippet:

```javascript
const WQL = window.require('wql-process-monitor');

WQL.createEventSink();

const processMonitor = WQL.subscribe({
  filterWindowsNoise: false,
  filter:  ["StarCitizen.exe"],
  whitelist: true,
});

processMonitor.on("creation", ([process, pid, filepath]) => {
...
});
```

The console log shows
```
Uncaught ERR_WQL_QUERY_FAILED
\AppData\Local\VerseGuide\app-0.5.3\resources\app\node_modules\wql-process-monitor\lib\processMonitor.cjs
```

Once it fails once, I have to log out of windows and log back in in order to make it work again. Restarting the app does not help.

I will try to dig a little bit deeper.
