### ISSUE TITLE
Type declaration not found

### ISSUE THREAD

**Issue by davidkhierl** [xan105/node-processMonitor#6]
![image](https://user-images.githubusercontent.com/25083033/170264086-bd7717dc-e62d-4115-b4a6-a0fc3fec6c24.png)

**Comment by xan105** [comment]
[This is supported starting with TypeScript 4.7](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#package-json-exports-imports-and-self-referencing)
I've added the needed _types_ field in package.json in v2.1.1
